// ════════════════════════════════════════════════════
// DADOS COMPLETOS — JANEIRO (161 registros)
// ════════════════════════════════════════════════════
const JAN = [
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Anderson" },
  { cat: "Active Directory (AD)", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Admin Center", fin: "Sim", h: 0.5, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.75, ana: "Anderson" },
  { cat: "Infra", fin: "Sim", h: 7, ana: "Anderson" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Anderson" },
  { cat: "Acesso Remoto", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Periféricos", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Anderson" },
  { cat: "Onedrive", fin: "Sim", h: 0.5, ana: "Anderson" },
  { cat: "Windows", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Config. Inicial", fin: "Sim", h: 0.75, ana: "Anderson" },
  { cat: "Autodesk", fin: "Sim", h: 0.5, ana: "Anderson" },
  { cat: "Autodesk", fin: "Sim", h: 0.5, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Anderson" },
  { cat: "Notebook", fin: "Sim", h: 0.75, ana: "Anderson" },
  { cat: "Antena wi-fi", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Anderson" },
  { cat: "Software", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Autodesk", fin: "Sim", h: 0.5, ana: "Anderson" },
  { cat: "Onedrive", fin: "Sim", h: 1.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Anderson" },
  { cat: "Impressoras", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Autodesk", fin: "Sim", h: 0.5, ana: "Anderson" },
  { cat: "Impressoras", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Anderson" },
  { cat: "Realocação", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Realocação", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Admin Center", fin: "Sim", h: 0.75, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Anderson" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Anderson" },
  { cat: "Autodesk", fin: "Sim", h: 0.5, ana: "Anderson" },
  { cat: "Realocação", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Instalação", fin: "Sim", h: 0.5, ana: "Anderson" },
  { cat: "Windows", fin: "Sim", h: 1.5, ana: "Anderson" },
  { cat: "Windows", fin: "Sim", h: 1, ana: "Anderson" },
  { cat: "Autodesk", fin: "Sim", h: 0.5, ana: "Anderson" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Onedrive", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Onedrive", fin: "Sim", h: 0.5, ana: "Anderson" },
  { cat: "Autodesk", fin: "Sim", h: 0.5, ana: "Anderson" },
  { cat: "Periféricos", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Active Directory (AD)", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Config. Inicial", fin: "Sim", h: 0.75, ana: "Anderson" },
  { cat: "Autodesk", fin: "Sim", h: 0.5, ana: "Anderson" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "CPU", fin: "Sim", h: 3, ana: "Anderson" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "E-mail / Outlook", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Anderson" },
  { cat: "Software", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Impressoras", fin: "Sim", h: 1.25, ana: "Anderson" },
  { cat: "Windows", fin: "Sim", h: 0.75, ana: "Anderson" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Simulação", fin: "Sim", h: 0.75, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.75, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Anderson" },
  { cat: "Active Directory (AD)", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Config. Inicial", fin: "Sim", h: 0.75, ana: "Anderson" },
  { cat: "Config. Inicial", fin: "Sim", h: 0.75, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Autodesk", fin: "Sim", h: 0.5, ana: "Anderson" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Anderson" },
  { cat: "Infraestrutura", fin: "Sim", h: 0.5, ana: "Anderson" },
  { cat: "Periféricos", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Anderson" },
  { cat: "Periféricos", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Impressoras", fin: "Sim", h: 0.5, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Anderson" },
  { cat: "Infraestrutura", fin: "Sim", h: 0.75, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Onedrive", fin: "Sim", h: 0.75, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Anderson" },
  { cat: "Periféricos", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Active Directory (AD)", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.75, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.75, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Anderson" },
  { cat: "Periféricos", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Firewall", fin: "Sim", h: 1.5, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Anderson" },
  { cat: "Webcam", fin: "Sim", h: 1, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Software", fin: "Sim", h: 0.75, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Anderson" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Anderson" },
  { cat: "Software", fin: "Sim", h: 1.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Anderson" },
  { cat: "Software", fin: "Sim", h: 1.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Onedrive", fin: "Sim", h: 0.75, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Onedrive", fin: "Sim", h: 0.75, ana: "Guilherme" },
  { cat: "Autodesk", fin: "Sim", h: 0.5, ana: "Anderson" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
];

// ════════════════════════════════════════════════════
// DADOS COMPLETOS — FEVEREIRO (116 registros)
// ════════════════════════════════════════════════════
const FEV = [
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Anderson" },
  { cat: "Periféricos", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Notebook", fin: "Sim", h: 2.5, ana: "Anderson" },
  { cat: "Onedrive", fin: "Sim", h: 2, ana: "Anderson" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Windows", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Monitor", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Software", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Anderson" },
  { cat: "Teams", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Impressoras", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Onedrive", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Onedrive", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Zepp", fin: "Sim", h: 0.5, ana: "Anderson" },
  { cat: "Notebook", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Anderson" },
  { cat: "Notebook", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Periféricos", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Windows", fin: "Sim", h: 2.5, ana: "Anderson" },
  { cat: "Notebook", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Devolução", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Onedrive", fin: "Sim", h: 0.75, ana: "Guilherme" },
  { cat: "VPN", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Windows", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Acesso Remoto", fin: "Sim", h: 0.5, ana: "Anderson" },
  { cat: "Software", fin: "Sim", h: 0.75, ana: "Anderson" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Anderson" },
  { cat: "Onedrive", fin: "Sim", h: 0.5, ana: "Anderson" },
  { cat: "Periféricos", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Windows", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Periféricos", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Acesso Remoto", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Emprestimo", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Anderson" },
  { cat: "Internet", fin: "Sim", h: 0.5, ana: "Anderson" },
  { cat: "Autodesk", fin: "Sim", h: 0.5, ana: "Anderson" },
  { cat: "Active Directory (AD)", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Admin Center", fin: "Sim", h: 0.5, ana: "Anderson" },
  { cat: "Infra", fin: "Sim", h: 0.5, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Windows", fin: "Sim", h: 0.5, ana: "Anderson" },
  { cat: "Config. Inicial", fin: "Sim", h: 0.75, ana: "Anderson" },
  { cat: "Onedrive", fin: "Sim", h: 1, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Infra", fin: "Sim", h: 0.75, ana: "Guilherme" },
  { cat: "Periféricos", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Autodesk", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Banco de Dados", fin: "Sim", h: 1.5, ana: "Guilherme" },
  { cat: "Onedrive", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Onedrive", fin: "Sim", h: 0.75, ana: "Anderson" },
  { cat: "Banco de Dados", fin: "Sim", h: 1.5, ana: "Anderson" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Software", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 1.25, ana: "Anderson" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Onedrive", fin: "Sim", h: 0.5, ana: "Anderson" },
  { cat: "Acesso Remoto", fin: "Sim", h: 0.5, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Windows", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
];

// ════════════════════════════════════════════════════
// DADOS REAIS — MARÇO (191 registros)
// ════════════════════════════════════════════════════
const MAR = [
  // 02/03
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Anderson" },
  { cat: "Autodesk", fin: "Sim", h: 0.5, ana: "Anderson" },
  { cat: "Software", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Onedrive", fin: "Sim", h: 2.5, ana: "Anderson" },
  { cat: "Notebook", fin: "Sim", h: 1, ana: "Anderson" },
  { cat: "Mapeamento", fin: "Sim", h: 0.5, ana: "Anderson" },
  // 03/03
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.5, ana: "Guilherme" },
  // 04/03
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Anderson" },
  { cat: "Notebook", fin: "Sim", h: 2.5, ana: "Anderson" },
  { cat: "Servidor", fin: "Sim", h: 0.25, ana: "Anderson" },
  // 05/03
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Office", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Google Earth", fin: "Sim", h: 0.25, ana: "Guilherme" },
  // 06/03
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Rede", fin: "Sim", h: 0.75, ana: "Guilherme" },
  // 09/03
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Hardware", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Rede", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  // 10/03
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Empréstimo", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Empréstimo", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Devolução", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  // 11/03
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Empréstimo", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  // 12/03
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Active Directory (AD)", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Active Directory (AD)", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Empréstimo", fin: "Sim", h: 0.25, ana: "Guilherme" },
  // 13/03
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Instalação", fin: "Sim", h: 0.75, ana: "Guilherme" },
  { cat: "Autodesk", fin: "Sim", h: 0.75, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Onedrive", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Notebook", fin: "Sim", h: 3, ana: "Guilherme" },
  // 16/03
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Instalação", fin: "Sim", h: 0.75, ana: "Guilherme" },
  { cat: "Configurações", fin: "Sim", h: 0.75, ana: "Guilherme" },
  { cat: "Autodesk", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Rede", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Configurações", fin: "Sim", h: 0.75, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 3, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Rede", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Rede", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Rede", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Rede", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.5, ana: "Guilherme" },
  // 17/03
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Servidor", fin: "Sim", h: 0.75, ana: "Guilherme" },
  { cat: "Infra", fin: "Sim", h: 2.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  // 18/03
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Impressão", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Autodesk", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  // 19/03
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Autodesk", fin: "Sim", h: 0.75, ana: "Guilherme" },
  { cat: "Empréstimo", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Empréstimo", fin: "Sim", h: 0.25, ana: "Guilherme" },
  // 20/03
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Active Directory (AD)", fin: "Sim", h: 0.25, ana: "Guilherme" },
  // 23/03
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Equipamento", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Partição", fin: "Sim", h: 0.75, ana: "Guilherme" },
  { cat: "Empréstimo", fin: "Sim", h: 0.25, ana: "Guilherme" },
  // 24/03
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Onedrive", fin: "Sim", h: 0.5, ana: "Guilherme" },
  // 25/03
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Equipamento", fin: "Sim", h: 0.75, ana: "Guilherme" },
  { cat: "Empréstimo", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  // 26/03
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Autodesk", fin: "Sim", h: 0.75, ana: "Guilherme" },
  { cat: "Impressão", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Configurações", fin: "Sim", h: 2, ana: "Guilherme" },
  { cat: "Hardware", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "EntraID", fin: "Sim", h: 0.75, ana: "Guilherme" },
  // 27/03
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  // 37 instalações QGIS
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Equipamento", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  // 30/03
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Equipamento", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Windows", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Onedrive", fin: "Sim", h: 0.75, ana: "Guilherme" },
  // 31/03
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Exchange", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Exchange", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Empréstimo", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Empréstimo", fin: "Sim", h: 0.25, ana: "Guilherme" },
];

// ════════════════════════════════════════════════════
// DADOS COMPLETOS — ABRIL (113 registros)
// ════════════════════════════════════════════════════
const ABR = [
  // 01/04
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  // 02/04
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Autodesk", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Onedrive", fin: "Sim", h: 0.75, ana: "Guilherme" },
  // 06/04
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Teams", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Certificado", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  // 07/04
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Empréstimo", fin: "Sim", h: 0.25, ana: "Guilherme" },
  // 08/04
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Equipamento", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 1, ana: "Guilherme" },
  // 09/04
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Onedrive", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Autodesk", fin: "Sim", h: 0.75, ana: "Guilherme" },
  // 10/04
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Empréstimo", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Empréstimo", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Hardware", fin: "Sim", h: 1.5, ana: "Guilherme" },
  // 13/04
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Realocação", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Notebook", fin: "Sim", h: 0.75, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sienge", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sienge", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sienge", fin: "Sim", h: 0.5, ana: "Guilherme" },
  // 14/04
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  // 15/04
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Equipamento", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  // 16/04
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Onedrive", fin: "Sim", h: 2, ana: "Guilherme" },
  // 17/04
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Mapeamento", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Windows", fin: "Sim", h: 2.5, ana: "Guilherme" },
  // 20/04
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  // 22/04
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Windows", fin: "Sim", h: 1.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Autodesk", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Autodesk", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  // 23/04
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme / Luiz" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme / Luiz" },
  { cat: "Autodesk", fin: "Sim", h: 0.75, ana: "Guilherme / Luiz" },
  { cat: "Sharepoint", fin: "Sim", h: 1, ana: "Guilherme / Luiz" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme / Luiz" },
  { cat: "Onedrive", fin: "Sim", h: 0.75, ana: "Guilherme / Luiz" },
  { cat: "Sharepoint", fin: "Sim", h: 1, ana: "Guilherme / Luiz" },
  { cat: "Windows", fin: "Sim", h: 1.5, ana: "Guilherme / Luiz" },
  // 24/04
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Windows", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Windows", fin: "Sim", h: 2, ana: "Guilherme" },
  // 27/04
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  // 28/04
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme / Luiz" },
  { cat: "Windows", fin: "Sim", h: 1.5, ana: "Guilherme / Luiz" },
  { cat: "Autodesk", fin: "Sim", h: 0.75, ana: "Guilherme / Luiz" },
  // 29/04
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Microsoft", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Autodesk", fin: "Sim", h: 1, ana: "Guilherme" },
  // 30/04
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Servidor", fin: "Sim", h: 0.75, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
];

// ════════════════════════════════════════════════════
// DADOS — MAIO (139 registros)
// ════════════════════════════════════════════════════
const MAI = [
  // 04/05
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Realocação", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Empréstimo", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Periféricos", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Windows", fin: "Sim", h: 2, ana: "Guilherme" },
  { cat: "Autodesk", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Windows", fin: "Sim", h: 1.5, ana: "Guilherme / Luiz" },
  { cat: "Admin Center", fin: "Sim", h: 0.5, ana: "Guilherme" },
  // 05/05
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme / Luiz" },
  { cat: "Windows", fin: "Sim", h: 0.5, ana: "Guilherme / Luiz" },
  { cat: "Equipamento", fin: "Sim", h: 1, ana: "Guilherme / Luiz" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme / Luiz" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme / Luiz" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme / Luiz" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme / Luiz" },
  { cat: "Autodesk", fin: "Sim", h: 0.75, ana: "Guilherme / Luiz" },
  { cat: "Windows", fin: "Sim", h: 2, ana: "Guilherme / Luiz" },
  // 06/05
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Servidor", fin: "Sim", h: 4.25, ana: "Guilherme / Hamilton" },
  // 07/05
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  // 08/05
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Impressora", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  // 11/05
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  // 12/05
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme / Luiz" },
  { cat: "MS365", fin: "Sim", h: 0.25, ana: "Guilherme / Luiz" },
  { cat: "Empréstimo", fin: "Sim", h: 0.25, ana: "Guilherme / Luiz" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme / Luiz" },
  { cat: "Onedrive", fin: "Sim", h: 0.5, ana: "Guilherme / Luiz" },
  { cat: "MS365", fin: "Sim", h: 0.25, ana: "Guilherme / Luiz" },
  { cat: "Realocação", fin: "Sim", h: 1.25, ana: "Guilherme / Luiz" },
  // 13/05
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.75, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Teams", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Rede", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Teams", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Estação", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Estação", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Windows", fin: "Sim", h: 2, ana: "Guilherme" },
  // 14/05
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.75, ana: "Guilherme" },
  { cat: "LocaWeb", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Empréstimo", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Empréstimo", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Windows", fin: "Sim", h: 0.75, ana: "Guilherme" },
  { cat: "Windows", fin: "Sim", h: 0.75, ana: "Guilherme" },
  { cat: "Windows", fin: "Sim", h: 2, ana: "Guilherme" },
  // 15/05
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Equipamento", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "LocaWeb", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "ArcGis", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Teams", fin: "Sim", h: 1, ana: "Guilherme" },
  // 18/05
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Realocação", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Impressora", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.5, ana: "Guilherme" },
  // 19/05
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme / Luiz" },
  { cat: "Servidor", fin: "Sim", h: 1.5, ana: "Guilherme / Luiz" },
  { cat: "Mesas", fin: "Sim", h: 1, ana: "Guilherme / Luiz" },
  { cat: "Desktop", fin: "Sim", h: 1.5, ana: "Guilherme / Luiz" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme / Luiz" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme / Luiz" },
  // 20/05
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Windows", fin: "Sim", h: 2, ana: "Guilherme" },
  // 21/05
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  // 22/05
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Empréstimo", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  // 25/05
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Autodesk", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Empréstimo", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Autodesk", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Acesso Remoto", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Onedrive", fin: "Sim", h: 0.25, ana: "Guilherme" },
  // 26/05
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Equipamento", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Acesso Remoto", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Windows", fin: "Sim", h: 2, ana: "Guilherme" },
  { cat: "Impressora", fin: "Sim", h: 0.25, ana: "Guilherme" },
  // 27/05
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Autodesk", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Rede", fin: "Sim", h: 0.5, ana: "Guilherme" },
  // 28/05
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme / Luiz" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme / Luiz" },
  { cat: "Onedrive", fin: "Sim", h: 0.75, ana: "Guilherme / Luiz" },
  { cat: "Bitdefender", fin: "Sim", h: 1, ana: "Guilherme / Luiz" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme / Luiz" },
  { cat: "Equipamento", fin: "Sim", h: 2, ana: "Guilherme / Luiz" },
  // 29/05
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Autodesk", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Active Directory (AD)", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Active Directory (AD)", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Active Directory (AD)", fin: "Sim", h: 0.25, ana: "Guilherme" },
];

// ════════════════════════════════════════════════════
// DADOS COMPLETOS — JUNHO
// ════════════════════════════════════════════════════
const JUN = [
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Luiz" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Luiz" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Luiz" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Luiz" },
  { cat: "Sharepoint", fin: "Sim", h: 0.75, ana: "Guilherme" },
  { cat: "Autodesk", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Onedrive", fin: "Sim", h: 1.5, ana: "Guilherme" },
  { cat: "Click Up", fin: "Sim", h: 0.75, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "CFTV", fin: "Sim", h: 1.25, ana: "Guilherme" },
  { cat: "CFTV", fin: "Sim", h: 0.75, ana: "Guilherme" },
  { cat: "CFTV", fin: "Sim", h: 0.75, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Windows", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Luiz" },
  { cat: "Hardware", fin: "Sim", h: 0.25, ana: "Luiz" },
  { cat: "Admin Center", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Outlook", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Outlook", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Outlook", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 2.5, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Active Directory", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Outlook", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Windows", fin: "Sim", h: 2.5, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Windows", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Windows", fin: "Sim", h: 2, ana: "Guilherme" },
  { cat: "Windows", fin: "Sim", h: 0.75, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "CFTV", fin: "Sim", h: 0.75, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Luiz" },
  { cat: "Impressora", fin: "Sim", h: 1, ana: "Luiz" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Luiz" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Onedrive", fin: "Sim", h: 0.75, ana: "Guilherme" },
  { cat: "Windows", fin: "Sim", h: 1.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 1.5, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Autodesk", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Impressora", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Impressora", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Servidor", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Luiz" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Luiz" },
  { cat: "Sharepoint", fin: "Sim", h: 1, ana: "Luiz" },
  { cat: "software", fin: "Sim", h: 0.75, ana: "Luiz" },
  { cat: "Windows", fin: "Sim", h: 1, ana: "Luiz" },
  { cat: "Servidor", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Windows", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Empréstimo", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "LocaWeb", fin: "Sim", h: 0.75, ana: "Guilherme" },
  { cat: "Windows", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Outlook", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Empréstimo", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Mouse", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Windows", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Windows", fin: "Sim", h: 4, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Equipamentos", fin: "Sim", h: 1.5, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Luiz" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Empréstimo", fin: "Sim", h: 0.25, ana: "Luiz" },
  { cat: "Empréstimo", fin: "Sim", h: 0.25, ana: "Luiz" },
  { cat: "Onedrive", fin: "Sim", h: 1, ana: "Luiz" },
  { cat: "Hardware", fin: "Sim", h: 0.25, ana: "Luiz" },
  { cat: "Onedrive", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Hardware", fin: "Sim", h: 1, ana: "Luiz" },
  { cat: "Onedrive", fin: "Sim", h: 1, ana: "Luiz" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Windows", fin: "Sim", h: 1.5, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Autodesk", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "LocaWeb", fin: "Sim", h: 1.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Impressoras", fin: "Sim", h: 0.25, ana: "Guilherme" },
];

// ════════════════════════════════════════════════════
// DADOS COMPLETOS — JULHO
// ════════════════════════════════════════════════════
const JUL = [
  { cat: "Checklist", fin: "Sim", h: 1.0, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Servidor", fin: "Sim", h: 0.75, ana: "Guilherme" },
  { cat: "Equipamento", fin: "Sim", h: 2.0, ana: "Luiz" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.75, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Hardware", fin: "Sim", h: 0.75, ana: "Luiz" },
  { cat: "Checklist", fin: "Sim", h: 1.0, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Impressora", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1.0, ana: "Guilherme" },
  { cat: "Autodesk", fin: "Sim", h: 1.5, ana: "Guilherme" },
  { cat: "Autodesk", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Acesso remoto", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Acesso remoto", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Mapeamento", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Celular", fin: "Sim", h: 0.25, ana: "Luiz" },
  { cat: "Checklist", fin: "Sim", h: 1.0, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Mapeamento", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Autodesk", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Mapeamento", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Impressora", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1.0, ana: "Guilherme" },
  { cat: "Hardware", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Onedrive", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1.0, ana: "Luiz" },
  { cat: "Impressora", fin: "Sim", h: 1.0, ana: "Luiz" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Equipamento", fin: "Sim", h: 2.0, ana: "Luiz" },
  { cat: "Software", fin: "Sim", h: 1.0, ana: "Luiz" },
  { cat: "Checklist", fin: "Sim", h: 1.0, ana: "Guilherme" },
  { cat: "Windows", fin: "Sim", h: 2.0, ana: "Guilherme" },
  { cat: "Windows", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Celular", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Autodesk", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.25, ana: "Luiz" },
  { cat: "Rede", fin: "Sim", h: 1.0, ana: "Luiz" },
  { cat: "Checklist", fin: "Sim", h: 1.0, ana: "Luiz" },
  { cat: "Periféricos", fin: "Sim", h: 1.0, ana: "Luiz" },
  { cat: "Equipamento", fin: "Sim", h: 1.0, ana: "Luiz" },
  { cat: "Software", fin: "Sim", h: 1.0, ana: "Luiz" },
  { cat: "Internet", fin: "Sim", h: 1.0, ana: "Guilherme" },
  { cat: "Celular", fin: "Sim", h: 0.25, ana: "Luiz" },
  { cat: "Checklist", fin: "Sim", h: 1.0, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Hardware", fin: "Sim", h: 1.5, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1.0, ana: "Luiz" },
  { cat: "Hardware", fin: "Sim", h: 0.25, ana: "Luiz" },
  { cat: "Periféricos", fin: "Sim", h: 0.5, ana: "Luiz" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1.0, ana: "Guilherme" },
  { cat: "Servidor", fin: "Sim", h: 0.75, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1.0, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 1.0, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1.0, ana: "Luiz" },
  { cat: "Windows", fin: "Sim", h: 1.0, ana: "Luiz" },
  { cat: "Internet", fin: "Sim", h: 0.5, ana: "Luiz" },
  { cat: "Checklist", fin: "Sim", h: 1.0, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Onedrive", fin: "Sim", h: 1.0, ana: "Guilherme" },
  { cat: "Periféricos", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Onedrive", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1.0, ana: "Guilherme" },
  { cat: "Emprestimo", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Onedrive", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Autodesk", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Acesso remoto", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1.0, ana: "Luiz" },
  { cat: "Periféricos", fin: "Sim", h: 0.5, ana: "Luiz" },
  { cat: "Software", fin: "Sim", h: 0.25, ana: "Luiz" },
  { cat: "Acesso remoto", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Hardware", fin: "Sim", h: 2.0, ana: "Luiz" },
  { cat: "Software", fin: "Sim", h: 0.25, ana: "Luiz" },
  { cat: "Checklist", fin: "Sim", h: 1.0, ana: "Guilherme" },
  { cat: "Emprestimo", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Celular", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Acesso remoto", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Hardware", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Windows", fin: "Sim", h: 2.0, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 1.0, ana: "Guilherme" },
  { cat: "Rede", fin: "Sim", h: 0.5, ana: "Luiz" },
  { cat: "Checklist", fin: "Sim", h: 1.0, ana: "Guilherme" },
  { cat: "Hardware", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Hardware", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Emprestimo", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Acesso remoto", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1.0, ana: "Guilherme" },
  { cat: "Acesso remoto", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Monitor", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Windows", fin: "Sim", h: 2.0, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Equipamento", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Hardware", fin: "Sim", h: 0.25, ana: "Luiz" },
  { cat: "Acesso remoto", fin: "Sim", h: 0.5, ana: "Luiz" },
  { cat: "Rede", fin: "Sim", h: 1.0, ana: "Luiz" },
  { cat: "Checklist", fin: "Sim", h: 1.0, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Equipamento", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Windows", fin: "Sim", h: 1.0, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Impressora", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Windows", fin: "Sim", h: 1.25, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1.0, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1.0, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.5, ana: "Guilherme" }, 
  { cat: "Impressora", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 5, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Hamilton" },
  { cat: "Active Directory", fin: "Sim", h: 0.25, ana: "Hamilton" },
];

const AGO = [
  { cat: "Checklist", fin: "Sim", h: 1.0, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.75, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 1.0, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 1.0, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Onedrive", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1.0, ana: "Luiz" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Luiz" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Luiz" },
  { cat: "Periféricos", fin: "Sim", h: 1.0, ana: "Luiz" },
  { cat: "Software", fin: "Sim", h: 0.25, ana: "Guilherme / Luiz Pelais" },
  { cat: "Software", fin: "Sim", h: 0.25, ana: "Luiz" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Luiz" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Luiz" },
  { cat: "Checklist", fin: "Sim", h: 1.0, ana: "Guilherme" },
  { cat: "Autodesk", fin: "Sim", h: 0.75, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.75, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Servidor", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Hardware", fin: "Sim", h: 1.25, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1.0, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1.0, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1.0, ana: "Luiz" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Luiz" },
  { cat: "Autodesk", fin: "Sim", h: 0.5, ana: "Luiz" },
  { cat: "Windows", fin: "Sim", h: 3.0, ana: "Guilherme / Luiz Pelais" },
  { cat: "Checklist", fin: "Sim", h: 1.0, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 1.0, ana: "Guilherme" },
  { cat: "Equipamento", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1.0, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Equipamento", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Equipamento", fin: "Sim", h: 1.0, ana: "Guilherme" },
  { cat: "Documentação", fin: "Sim", h: 1.0, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Equipamento", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Impressora", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1.0, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Equipamento", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Windows", fin: "Sim", h: 0.75, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1.0, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Active Directory", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Servidor", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1.0, ana: "Luiz" },
  { cat: "Software", fin: "Sim", h: 0.25, ana: "Luiz" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Luiz" },
  { cat: "MS365", fin: "Sim", h: 0.25, ana: "Luiz" },
  { cat: "MS365", fin: "Sim", h: 0.25, ana: "Luiz" },
  { cat: "Servidor", fin: "Sim", h: 0.25, ana: "Luiz" },
  { cat: "Checklist", fin: "Sim", h: 1.0, ana: "Guilherme" },
  { cat: "Windows", fin: "Sim", h: 2.0, ana: "Guilherme" },
  { cat: "Equipamento", fin: "Sim", h: 1.0, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1.0, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Equipamento", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Servidor", fin: "Sim", h: 1.0, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1.0, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Windows", fin: "Sim", h: 3.0, ana: "Guilherme" },
  { cat: "Equipamento", fin: "Sim", h: 0.75, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Equipamento", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Equipamento", fin: "Sim", h: 2.0, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1.0, ana: "Guilherme" },
  { cat: "Windows", fin: "Sim", h: 1.0, ana: "Guilherme" },
  { cat: "Autodesk", fin: "Sim", h: 0.75, ana: "Guilherme" },
  { cat: "Windows", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1.0, ana: "Luiz" },
  { cat: "MS365", fin: "Sim", h: 0.3, ana: "Guilherme / Luiz Pelais" },
  { cat: "Equipamento", fin: "Sim", h: 0.75, ana: "Luiz" },
  { cat: "Software", fin: "Sim", h: 0.75, ana: "Luiz" },
  { cat: "Checklist", fin: "Sim", h: 1.0, ana: "Guilherme" },
  { cat: "Equipamento", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1.0, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.75, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Windows", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1.0, ana: "Guilherme" },
  { cat: "Admin Center", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.5, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Checklist", fin: "Sim", h: 1.0, ana: "Guilherme" },
  { cat: "Sharepoint", fin: "Sim", h: 0.25, ana: "Guilherme" },
  { cat: "Autodesk", fin: "Sim", h: 0.75, ana: "Guilherme" },
  { cat: "Hardware", fin: "Sim", h: 1.5, ana: "Guilherme" },
  { cat: "Windows", fin: "Sim", h: 2.0, ana: "Guilherme" },
  { cat: "Software", fin: "Sim", h: 0.25, ana: "Guilherme" },
];

// ════════════════════════════════════════════════════
// FUNÇÕES AUXILIARES
// ════════════════════════════════════════════════════
const sumH = (a) => +a.reduce((s, r) => s + r.h, 0).toFixed(1);
const countFin = (a, v) => a.filter((r) => r.fin === v).length;

function catMap(arr) {
  const m = {};
  arr.forEach((r) => {
    m[r.cat] = (m[r.cat] || 0) + 1;
  });
  return m;
}
function anaMap(arr) {
  const m = {};
  arr.forEach((r) => {
    m[r.ana] = (m[r.ana] || 0) + 1;
  });
  return m;
}
function topN(obj, n) {
  return Object.entries(obj)
    .sort((a, b) => b[1] - a[1])
    .slice(0, n);
}
function topKey(obj) {
  return Object.entries(obj).sort((a, b) => b[1] - a[1])[0][0];
}

// ════════════════════════════════════════════════════
// CÁLCULOS GERAIS
// ════════════════════════════════════════════════════
const jT = JAN.length,
  fT = FEV.length,
  mT = MAR.length,
  aT = ABR.length,
  maT = MAI.length,
  juT = JUN.length,
  julT = JUL.length,
  agoT = AGO.length;
const total = jT + fT + mT + aT + maT + juT + julT + agoT;

const jFin = countFin(JAN, "Sim"),
  fFin = countFin(FEV, "Sim"),
  mFin = countFin(MAR, "Sim"),
  aFin = countFin(ABR, "Sim"),
  maFin = countFin(MAI, "Sim"),
  juFin = countFin(JUN, "Sim"),
  julFin = countFin(JUL, "Sim"),
  agoFin = countFin(AGO, "Sim");

const jNF = countFin(JAN, "Não"),
  fNF = countFin(FEV, "Não"),
  mNF = countFin(MAR, "Não"),
  aNF = countFin(ABR, "Não"),
  maNF = countFin(MAI, "Não"),
  juNF = countFin(JUN, "Não"),
  julNF = countFin(JUL, "Não"),
  agoNF = countFin(AGO, "Não");

const totalFin = jFin + fFin + mFin + aFin + maFin + juFin + julFin + agoFin;
const taxa = Math.round((totalFin / total) * 100);

const jH = sumH(JAN),
  fH = sumH(FEV),
  mH = sumH(MAR),
  aH = sumH(ABR),
  maH = sumH(MAI),
  juH = sumH(JUN),
  julH = sumH(JUL),
  agoH = sumH(AGO);
const totalH = +(jH + fH + mH + aH + maH + juH + julH + agoH).toFixed(1);

const jCM = catMap(JAN),
  fCM = catMap(FEV),
  mCM = catMap(MAR),
  aCM = catMap(ABR),
  maCM = catMap(MAI),
  juCM = catMap(JUN),
  julCM = catMap(JUL),
  agoCM = catMap(AGO);
const allCM = catMap([
  ...JAN,
  ...FEV,
  ...MAR,
  ...ABR,
  ...MAI,
  ...JUN,
  ...JUL,
  ...AGO,
]);

const jAM = anaMap(JAN),
  fAM = anaMap(FEV),
  mAM = anaMap(MAR),
  aAM = anaMap(ABR),
  maAM = anaMap(MAI),
  juAM = anaMap(JUN),
  julAM = anaMap(JUL),
  agoAM = anaMap(AGO);
const allAM = anaMap([
  ...JAN,
  ...FEV,
  ...MAR,
  ...ABR,
  ...MAI,
  ...JUN,
  ...JUL,
  ...AGO,
]);

const top10 = topN(allCM, 10);
const top6keys = topN(allCM, 6).map((e) => e[0]);

const meses = [
  { n: "Janeiro", v: jT },
  { n: "Fevereiro", v: fT },
  { n: "Março", v: mT },
  { n: "Abril", v: aT },
  { n: "Maio", v: maT },
  { n: "Junho", v: juT },
  { n: "Julho", v: julT },
  { n: "Agosto", v: agoT },
];
const topMes = [...meses].sort((a, b) => b.v - a.v)[0];

// ════════════════════════════════════════════════════
// PREENCHER KPIs
// ════════════════════════════════════════════════════
document.getElementById("kTotal").textContent = total;
document.getElementById("kTaxa").textContent = taxa + "%";
document.getElementById("kHoras").textContent = totalH + "h";
document.getElementById("kMes").textContent = topMes.n;
document.getElementById("kMesSub").textContent = topMes.v + " chamados";
document.getElementById("kCat").textContent = top10[0][0];
document.getElementById("kCatSub").textContent = top10[0][1] + " ocorrências";

// ════════════════════════════════════════════════════
// PREENCHER CARDS MENSAIS
// ════════════════════════════════════════════════════
[
  ["j1", jT],
  ["j2", jFin],
  ["j3", jNF],
  ["j4", jH + "h"],
  ["j5", topKey(jAM)],
  ["j6", topKey(jCM)],
  ["j7", "20 dias"],
  ["f1", fT],
  ["f2", fFin],
  ["f3", fNF],
  ["f4", fH + "h"],
  ["f5", topKey(fAM)],
  ["f6", topKey(fCM)],
  ["f7", "19 dias"],
  ["m1", mT],
  ["m2", mFin],
  ["m3", mNF],
  ["m4", mH + "h"],
  ["m5", topKey(mAM)],
  ["m6", topKey(mCM)],
  ["m7", "21 dias"],
  ["a1", aT],
  ["a2", aFin],
  ["a3", aNF],
  ["a4", aH + "h"],
  ["a5", topKey(aAM)],
  ["a6", topKey(aCM)],
  ["a7", "20 dias"],
  ["ma1", maT],
  ["ma2", maFin],
  ["ma3", maNF],
  ["ma4", maH + "h"],
  ["ma5", topKey(maAM)],
  ["ma6", topKey(maCM)],
  ["ma7", "20 dias"],
  ["jun1", juT],
  ["jun2", juFin],
  ["jun3", juNF],
  ["jun4", juH + "h"],
  ["jun5", topKey(juAM)],
  ["jun6", topKey(juCM)],
  ["jun7", "22 dias"],
  ["jul1", julT],
  ["jul2", julFin],
  ["jul3", julNF],
  ["jul4", julH + "h"],
  ["jul5", topKey(julAM)],
  ["jul6", topKey(julCM)],
  ["jul7", "24 dias"],
  ["ago1", agoT],
  ["ago2", agoFin],
  ["ago3", agoNF],
  ["ago4", agoH + "h"],
  ["ago5", topKey(agoAM)],
  ["ago6", topKey(agoCM)],
  ["ago7", "21 dias"],
].forEach(([id, val]) => {
  const el = document.getElementById(id);
  if (el) el.textContent = val;
});

// ════════════════════════════════════════════════════
// CHART.JS — CONFIGURAÇÕES GLOBAIS
// ════════════════════════════════════════════════════
Chart.defaults.color = "#7880a0";
Chart.defaults.font.family = "'Segoe UI', system-ui, sans-serif";
Chart.defaults.font.size = 12;

const grid = "rgba(0,0,0,0.05)";
const janC = "#4f8ef7";
const fevC = "#8b5cf6";
const marC = "#10d9a0";
const abrC = "#d35400";
const maiC = "#16a085";
const junC = "#8e44ad";
const julC = "#e67e22"; // Nova Cor de Julho
const agoC = "#e84393"; // Nova Cor de Agosto

// ─── VOLUME POR MÊS ──────────────────────────────
new Chart(document.getElementById("cVolume"), {
  type: "bar",
  data: {
    labels: [
      "Janeiro",
      "Fevereiro",
      "Março",
      "Abril",
      "Maio",
      "Junho",
      "Julho",
      "Agosto",
    ],
    datasets: [
      {
        label: "Chamados",
        data: [jT, fT, mT, aT, maT, juT, julT, agoT],
        backgroundColor: [janC, fevC, marC, abrC, maiC, junC, julC, agoC],
        borderRadius: 8,
        borderSkipped: false,
      },
    ],
  },
  options: {
    responsive: true,
    maintainAspectRatio: false,
    plugins: { legend: { display: false } },
    scales: {
      x: { grid: { color: grid } },
      y: { grid: { color: grid }, beginAtZero: true },
    },
  },
});

// ─── HORAS POR MÊS ───────────────────────────────
new Chart(document.getElementById("cHoras"), {
  type: "bar",
  data: {
    labels: [
      "Janeiro",
      "Fevereiro",
      "Março",
      "Abril",
      "Maio",
      "Junho",
      "Julho",
      "Agosto",
    ],
    datasets: [
      {
        label: "Horas",
        data: [jH, fH, mH, aH, maH, juH, julH, agoH],
        backgroundColor: [
          "rgba(245,200,66,.85)",
          "rgba(245,200,66,.65)",
          "rgba(245,200,66,.45)",
          "rgba(211,84,0,.75)",
          "rgba(22,160,133,.80)",
          "rgba(142,68,173,.85)",
          "rgba(230,126,34,.85)",
          "rgba(232,67,147,.85)",
        ],
        borderRadius: 8,
        borderSkipped: false,
      },
    ],
  },
  options: {
    responsive: true,
    maintainAspectRatio: false,
    plugins: { legend: { display: false } },
    scales: {
      x: { grid: { color: grid } },
      y: { grid: { color: grid }, beginAtZero: true },
    },
  },
});

// ─── TOP 10 CATEGORIAS ───────────────────────────
new Chart(document.getElementById("cCats"), {
  type: "bar",
  data: {
    labels: top10.map((e) => e[0]),
    datasets: [
      {
        label: "Chamados",
        data: top10.map((e) => e[1]),
        backgroundColor: [
          "#4f8ef7",
          "#8b5cf6",
          "#10d9a0",
          "#f5c842",
          "#f4714a",
          "#38bdf8",
          "#a78bfa",
          "#34d399",
          "#fbbf24",
          "#fb7185",
        ],
        borderRadius: 6,
        borderSkipped: false,
      },
    ],
  },
  options: {
    indexAxis: "y",
    responsive: true,
    maintainAspectRatio: false,
    plugins: { legend: { display: false } },
    scales: {
      x: { grid: { color: grid }, beginAtZero: true },
      y: { grid: { color: grid }, ticks: { font: { size: 11 } } },
    },
  },
});

// ─── ANALISTAS — BARRAS CUSTOMIZADAS ─────────────
const anaDiv = document.getElementById("anaDiv");
const anaMax = Math.max(...Object.values(allAM));
const anaColors = [janC, fevC, marC, abrC, maiC, junC, julC, agoC];
let anaIdx = 0;

Object.entries(allAM)
  .sort((a, b) => b[1] - a[1])
  .forEach(([nome, qtd]) => {
    const pct = Math.round((qtd / anaMax) * 100);
    const cor = anaColors[anaIdx % anaColors.length];
    anaIdx++;
    anaDiv.innerHTML += `
    <div class="ana-row">
      <div class="ana-name">${nome}</div>
      <div class="ana-track">
        <div class="ana-fill" style="width:${pct}%;background:${cor}">${qtd}</div>
      </div>
      <div class="ana-count" style="color:${cor}">${qtd}</div>
    </div>`;
  });

// ─── STATUS POR MÊS ──────────────────────────────
new Chart(document.getElementById("cStatus"), {
  type: "bar",
  data: {
    labels: [
      "Janeiro",
      "Fevereiro",
      "Março",
      "Abril",
      "Maio",
      "Junho",
      "Julho",
      "Agosto",
    ],
    datasets: [
      {
        label: "Finalizados",
        data: [jFin, fFin, mFin, aFin, maFin, juFin, julFin, agoFin],
        backgroundColor: marC,
        borderRadius: 6,
        borderSkipped: false,
      },
      {
        label: "Não Finalizados",
        data: [jNF, fNF, mNF, aNF, maNF, juNF, julNF, agoNF],
        backgroundColor: "#f4714a",
        borderRadius: 6,
        borderSkipped: false,
      },
    ],
  },
  options: {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: { display: true, labels: { color: "#7880a0", boxWidth: 12 } },
    },
    scales: {
      x: { stacked: true, grid: { color: grid } },
      y: { stacked: true, grid: { color: grid }, beginAtZero: true },
    },
  },
});

// ─── PIZZA — TOP 6 CATEGORIAS ────────────────────
const top6data = top6keys.map((k) => allCM[k] || 0);
const pizzaColors = [janC, fevC, marC, abrC, maiC, junC];

new Chart(document.getElementById("cPizza"), {
  type: "doughnut",
  data: {
    labels: top6keys,
    datasets: [
      {
        data: top6data,
        backgroundColor: pizzaColors,
        borderWidth: 2,
        borderColor: "#ffffff",
      },
    ],
  },
  options: {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: {
        display: true,
        position: "right",
        labels: { color: "#7880a0", boxWidth: 12, font: { size: 11 } },
      },
    },
    cutout: "60%",
  },
});

// ─── COMPARATIVO MENSAL TOP 6 ────────────────────
new Chart(document.getElementById("cCompare"), {
  type: "bar",
  data: {
    labels: top6keys,
    datasets: [
      {
        label: "Janeiro",
        data: top6keys.map((k) => jCM[k] || 0),
        backgroundColor: janC,
        borderRadius: 5,
        borderSkipped: false,
      },
      {
        label: "Fevereiro",
        data: top6keys.map((k) => fCM[k] || 0),
        backgroundColor: fevC,
        borderRadius: 5,
        borderSkipped: false,
      },
      {
        label: "Março",
        data: top6keys.map((k) => mCM[k] || 0),
        backgroundColor: marC,
        borderRadius: 5,
        borderSkipped: false,
      },
      {
        label: "Abril",
        data: top6keys.map((k) => aCM[k] || 0),
        backgroundColor: abrC,
        borderRadius: 5,
        borderSkipped: false,
      },
      {
        label: "Maio",
        data: top6keys.map((k) => maCM[k] || 0),
        backgroundColor: maiC,
        borderRadius: 5,
        borderSkipped: false,
      },
      {
        label: "Junho",
        data: top6keys.map((k) => juCM[k] || 0),
        backgroundColor: junC,
        borderRadius: 5,
        borderSkipped: false,
      },
      {
        label: "Julho",
        data: top6keys.map((k) => julCM[k] || 0),
        backgroundColor: julC,
        borderRadius: 5,
        borderSkipped: false,
      },
      {
        label: "Agosto",
        data: top6keys.map((k) => agoCM[k] || 0),
        backgroundColor: agoC,
        borderRadius: 5,
        borderSkipped: false,
      },
    ],
  },
  options: {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: { display: true, labels: { color: "#7880a0", boxWidth: 12 } },
    },
    scales: {
      x: { grid: { color: grid }, ticks: { font: { size: 11 } } },
      y: { grid: { color: grid }, beginAtZero: true },
    },
  },
});

// ─── TABELA: RANKING DE CATEGORIAS ───────────────
(function buildTable() {
  const allCats = [
    ...new Set([
      ...Object.keys(jCM),
      ...Object.keys(fCM),
      ...Object.keys(mCM),
      ...Object.keys(aCM),
      ...Object.keys(maCM),
      ...Object.keys(juCM),
      ...Object.keys(julCM),
      ...Object.keys(agoCM),
    ]),
  ];

  const rows = allCats
    .map((cat) => ({
      cat,
      jan: jCM[cat] || 0,
      feb: fCM[cat] || 0,
      mar: mCM[cat] || 0,
      abr: aCM[cat] || 0,
      mai: maCM[cat] || 0,
      jun: juCM[cat] || 0,
      jul: julCM[cat] || 0,
      ago: agoCM[cat] || 0,
      tot:
        (jCM[cat] || 0) +
        (fCM[cat] || 0) +
        (mCM[cat] || 0) +
        (aCM[cat] || 0) +
        (maCM[cat] || 0) +
        (juCM[cat] || 0) +
        (julCM[cat] || 0) +
        (agoCM[cat] || 0),
    }))
    .sort((a, b) => b.tot - a.tot)
    .slice(0, 15);

  const maxTot = rows[0].tot;
  const tbl = document.getElementById("catTbl");

  tbl.innerHTML = `
    <thead>
      <tr>
        <th>#</th>
        <th>Categoria</th>
        <th>Janeiro</th>
        <th>Fevereiro</th>
        <th>Março</th>
        <th>Abril</th>
        <th>Maio</th>
        <th>Junho</th>
        <th>Julho</th>
        <th>Agosto</th>
        <th>Total</th>
        <th>Distribuição</th>
      </tr>
    </thead>
    <tbody>
      ${rows
        .map(
          (r, i) => `
        <tr>
          <td style="color:var(--muted);font-weight:800">${i + 1}</td>
          <td style="font-weight:600">${r.cat}</td>
 <td>${r.jan > 0 ? `<span class="pill jan">${r.jan}</span>` : "—"}</td>

          <td>${r.feb > 0 ? `<span class="pill feb">${r.feb}</span>` : "—"}</td>
          <td>${r.mar > 0 ? `<span class="pill mar">${r.mar}</span>` : "—"}</td>
          <td>${r.abr > 0 ? `<span class="pill abr">${r.abr}</span>` : "—"}</td>
          <td>${r.mai > 0 ? `<span class="pill mai">${r.mai}</span>` : "—"}</td>
          <td>${r.jun > 0 ? `<span class="pill jun">${r.jun}</span>` : "—"}</td>
          <td>${r.jul > 0 ? `<span class="pill jul">${r.jul}</span>` : "—"}</td>
          <td>${r.ago > 0 ? `<span class="pill ago">${r.ago}</span>` : "—"}</td>

          <td style="font-weight:800;color:var(--text)">${r.tot}</td>
          <td>
            <div style="background:var(--card2);border-radius:4px;height:6px;width:120px;overflow:hidden;display:inline-block;vertical-align:middle">
              <div style="height:100%;width:${Math.round((r.tot / maxTot) * 100)}%;background:var(--accent);border-radius:4px"></div>
            </div>
          </td>
        </tr>`,
        )
        .join("")}
    </tbody>`;
})();
